### ISSUE TITLE
ModuleNotFoundError: No module named '__builtin__'

### ISSUE THREAD

**Issue by RohitMishraPU** [hfoffani/pddl-lib#16]
while trying to import  pddlpy it shows above error . what can be the solution for this?

**Comment by hfoffani** [comment]
Mmm... Which Python version are you using?
edit: That message implies a bug.. :-(
I'll have a look at it!

**Comment by hfoffani** [comment]
Hi Rohit,
I'm sorry but I could not reproduce it:
```
(pddltest) ~ $ 
(pddltest) ~ $ 
(pddltest) ~ $ pip install pddlpy
Collecting pddlpy
  Downloading pddlpy-0.1.9-py3-none-any.whl
Collecting antlr4-python3-runtime<4.8,>=4.7 (from pddlpy)
  Downloading antlr4-python3-runtime-4.7.tar.gz (110kB)
    100% |████████████████████████████████| 112kB 740kB/s 
Collecting antlr4-python2-runtime<4.8,>=4.7 (from pddlpy)
  Downloading antlr4-python2-runtime-4.7.tar.gz (110kB)
    100% |████████████████████████████████| 112kB 1.7MB/s 
Installing collected packages: antlr4-python3-runtime, antlr4-python2-runtime, pddlpy
  Running setup.py install for antlr4-python3-runtime ... done
  Running setup.py install for antlr4-python2-runtime ... done
Successfully installed antlr4-python2-runtime-4.7 antlr4-python3-runtime-4.7 pddlpy-0.1.9
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(pddltest) ~ $ 
(pddltest) ~ $ 
(pddltest) ~ $ python
Python 3.5.2 (default, Aug 18 2016, 17:30:22) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pddlpy
>>> 
>>> 
```
Could you please tell me which steps did you take? I think it could be related to a Python versions mixup.
Thanks!

**Comment by davidqiu1993** [comment]
python3 does not work.

The __builtin__ module was renamed to builtins in Python3.

please refer to this:
https://stackoverflow.com/questions/9047745/where-is-the-builtin-module-in-python3-why-was-it-renamed

**Comment by hfoffani** [comment]
Did you use `pip install pddlpy` from a python 3 environment?
If your default python is version 2.x then you probably need to install pddlpy with `pip3 install pddlpy`.
It would also help if you include the steps and output of your installation.

**Comment by davidqiu1993** [comment]
it seems like the antlr4 python package has to be blamed. I uninstalled that in python3 and installed that again manually, and it works.

but it turns out an even worse news came that I did not notice this lib does not have a solver....  :(

**Comment by hfoffani** [comment]
A solver is one of the most asked features.  I would probably work on it sometime in the next weeks.

**Comment by davidqiu1993** [comment]
that's fantastic, thank you.

also, i guess http://solver.planning.domains this one is very comprehensive, and they are also open-source (https://bitbucket.org/planning-researchers/cloud-solver). It is not quite easy to actually use this in a local environment, but I guess maybe you could borrow it a make it into your project.

**Comment by hfoffani** [comment]
issue #1 refers to a basic planner feature.

**Comment by aishniparab** [comment]
pip3 install pddlpy still produces the same error for me

my python version is 3.9.4. 

what is the fix for this?

**Comment by hfoffani** [comment]
> what is the fix for this?

It's been a while since I touched this project.
I'm reopening the issue and will take a look.

**Comment by SamraMehboob** [comment]
I'm facing same error, did anyone fixed it.
Please help.
Thanks.

**Comment by hfoffani** [comment]
Hi
Sorry people.
I'm working on it right now.
At the moment it doesn't pass the tests.
I'll let you know if I can solve these issues.
Thanks!

**Comment by hfoffani** [comment]
I've just published version 0.3.3 in pypi.
AFAICT, it works.

**Comment by fornakter** [comment]
> I've just published version 0.3.3 in pypi. AFAICT, it works.

How can i repair that problem?
Im try do make an app on Kivy. When i use some code on simple file, everything woks fine. But when i want to use same code on kivy app, theres an error with '__builtin__'

I check an files, when i recived error (from console) and theres code like:
```
try:
  import __buildin__
except:
  import __buildins__
```
and still dosent work.

I use Python 3.10.5
Pycharm
Win10

**Comment by hfoffani** [comment]
I haven't use Kivy before.
Would you mind to post the full traceback, please?
If that not possible, could you post a minimal test so I can reproduce the problem?
Thanks!

**Comment by fornakter** [comment]
Heres code.
Its simple app. 
https://github.com/fornakter/speed_test-kivy.git

**Comment by hfoffani** [comment]
I've tried it, but couldn't make it run.
What are the dependencies?
I've pip installed kivy and speedtest but it fails:
```
(kivy) ➜  speed_test-kivy git:(main) python main.py
[INFO   ] [Logger      ] Record log in /Users/hernan/.kivy/logs/kivy_22-07-31_3.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/Users/hernan/.pyenv/versions/kivy/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.9.6 (default, Aug  3 2021, 19:11:11) 
[Clang 12.0.5 (clang-1205.0.22.11)]
[INFO   ] [Python      ] Interpreter at "/Users/hernan/.pyenv/versions/kivy/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "/Users/hernan/Documents/Proyectos/speed_test-kivy/main.py", line 4, in <module>
     from only_test import speed_test
   File "/Users/hernan/Documents/Proyectos/speed_test-kivy/only_test.py", line 22, in <module>
     speed_test()
   File "/Users/hernan/Documents/Proyectos/speed_test-kivy/only_test.py", line 4, in speed_test
     test = speedtest.Speedtest()
 AttributeError: module 'speedtest' has no attribute 'Speedtest'
(kivy) ➜  speed_test-kivy git:(main) 
```

**Comment by fornakter** [comment]
I cut off everything what i can. Now i have error " 'LogFile' object has no attribute 'fileno' ".
But again - on 'only_test.py' everything works fine.
Anyway thanks for help.

**Comment by tute123456** [comment]
hi! I have the following problem, when I convert a .py file to exe (using auto-py-to-exe) I use the option of "one directory" / windows basic / with icon / additionals files (4 png (in the same folder where it is the .py)) file, but when I run the .exe it gives me a popup with errors "**ModuleNotFoundError: No module named '__builtin__'**"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "UdeSA Test ISP.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "speedtest.py", line 179, in <module>
  File "speedtest.py", line 166, in __init__
"_AttributeError: 'NoneType' object has no attribute 'fileno'_"

thx!

**Comment by hfoffani** [comment]
Hi!
What are the files "UdeSA Test ISP.py" and "speedtest.py" for?

**Comment by hfoffani** [comment]
Confirmed resolved on the current Python 3.11+ codebase. `__builtin__` is a Python 2-only module; the library no longer references it (verified: no `__builtin__`, `basestring`, `iteritems`, or `has_key` anywhere in the source). A regression guard (`tests/test_triage.py::test_no_python2_builtin_import`) now ensures it cannot creep back in.

This can be closed as fixed.
